## Modules to setup the webGUI and filesharing
cockpit_modules:
  - url: 'https://github.com/45Drives/cockpit-file-sharing/releases/download/v3.3.4/cockpit-file-sharing_3.3.4-1focal_all.deb'
    filename: 'cockpit-file-sharing.deb'
  - url: 'https://github.com/45Drives/cockpit-navigator/releases/download/v0.5.10/cockpit-navigator_0.5.10-1focal_all.deb'
    filename: 'cockpit-navigator.deb'
  - url: 'https://github.com/45Drives/cockpit-identities/releases/download/v0.1.12/cockpit-identities_0.1.12-1focal_all.deb'
    filename: 'cockpit-identities.deb'

## Users and Groups to be auto added 
cockpit_groups:
  - group: qbit
  - group: plex
  - group: k8s
  - group: samba
  - group: nfs


#Even with these users, still have to set the samba passwords
cockpit_users:
  - user: qbit
    password: 'k8s.pass'
    groups: ['qbit', 'samba', 'nfs']
  - user: plex
    password: "k8s.pass"
    groups: ['plex', 'samba', 'nfs']
  - user: k8s
    password: "k8s.pass"
    groups: ['k8s', 'samba', 'nfs']
  - user: torque
    password: torque.pass
    groups: ['sudo', 'samba', 'nfs']
  - user: fileshare-test
    password: default.pass
    groups: ['samba', 'nfs']
  - user: asseenontv
    password: default.pass
    groups: ['samba', 'nfs']

tailscale_authkey: "tskey-auth-kYaVJX2CNTRL-a9LVHzXYyXV63a4adK6LXVCGfWtCEvdx"

# Variables that an end user should likely never modify.
tailscale_debian_family_distros:
  - Ubuntu
  - Debian
  - Pop!_OS
  - OSMC

tailscale_centos_family_distros:
  - CentOS
  - OracleLinux
  - RedHat
  - Rocky
  - AlmaLinux

tailscale_opensuse_family_distros:
  - "openSUSE Leap"
  - "openSUSE Tumbleweed"

tailscale_package: tailscale
tailscale_service: tailscaled

tailscale_apt_dependencies:
  - gnupg2
  - gnupg-agent
  - apt-transport-https
  - python3-apt

tailscale_legacy_apt_dependencies:
  # Only install on legacy Debian systems
  - python-apt

tailscale_debian_distro:
  pop!_os: ubuntu
  ubuntu: ubuntu
  debian: debian
  osmc: debian

tailscale_apt_keyring_path: /usr/share/keyrings/tailscale-archive-keyring.gpg

tailscale_apt_deb: deb [signed-by={{ tailscale_apt_keyring_path }}] https://pkgs.tailscale.com/{{ release_stability | lower }}/{{ tailscale_debian_distro[ansible_distribution | lower] }} {{ ansible_distribution_release | lower }} main

tailscale_apt_signkey: https://pkgs.tailscale.com/{{ release_stability | lower }}/{{ tailscale_debian_distro[ansible_distribution | lower] }}/{{ ansible_distribution_release | lower }}.noarmor.gpg

tailscale_yum_dependencies:
  - yum-utils
  - gnupg2

tailscale_yum_repos:
  Amazon: https://pkgs.tailscale.com/{{ release_stability | lower }}/amazon-linux/{{ ansible_distribution_major_version }}/tailscale.repo
  CentOS: https://pkgs.tailscale.com/{{ release_stability | lower }}/centos/{{ ansible_distribution_major_version }}/tailscale.repo
  RedHat: https://pkgs.tailscale.com/{{ release_stability | lower }}/{{ "rhel" if ansible_distribution_major_version | int == 8 else "centos" }}/{{ ansible_distribution_major_version }}/tailscale.repo
  OracleLinux: https://pkgs.tailscale.com/{{ release_stability | lower }}/centos/{{ ansible_distribution_major_version }}/tailscale.repo
  Rocky: https://pkgs.tailscale.com/{{ release_stability | lower }}/centos/{{ ansible_distribution_major_version }}/tailscale.repo
  AlmaLinux: https://pkgs.tailscale.com/{{ release_stability | lower }}/centos/{{ ansible_distribution_major_version }}/tailscale.repo

tailscale_dnf_dependencies:
  - python-dnf

tailscale_dnf_plugins:
  - dnf-plugins-core

tailscale_dnf_repos:
  Amazon: https://pkgs.tailscale.com/{{ release_stability | lower }}/fedora/tailscale.repo
  Fedora: https://pkgs.tailscale.com/{{ release_stability | lower }}/fedora/tailscale.repo

tailscale_opensuse_leap_repository: "https://pkgs.tailscale.com/stable/opensuse/leap/{{ ansible_distribution_version }}/tailscale.repo"
tailscale_opensuse_tumbleweed_repository: https://pkgs.tailscale.com/stable/opensuse/tumbleweed/tailscale.repo

tailscale_original_distribution_major_version: "{{ ansible_distribution_major_version }}"