## Modules to setup the webGUI and filesharing
cockpit_modules:
  - url: 'https://github.com/45Drives/cockpit-file-sharing/releases/download/v3.3.4/cockpit-file-sharing_3.3.4-1focal_all.deb'
    filename: 'cockpit-file-sharing.deb'
  - url: 'https://github.com/45Drives/cockpit-navigator/releases/download/v0.5.10/cockpit-navigator_0.5.10-1focal_all.deb'
    filename: 'cockpit-navigator.deb'
  - url: 'https://github.com/45Drives/cockpit-identities/releases/download/v0.1.12/cockpit-identities_0.1.12-1focal_all.deb'
    filename: 'cockpit-identities.deb'

## Users and Groups to be auto added 
cockpit_groups:
  - group: qbit
  - group: plex
  - group: k8s
  - group: 7zip
  - group: nas-download-requests
  - group: nas-plex-media
  - group: nas-emulation-roms
  - group: nas-emulation
  - group: nas-emulation-roms-readonly
  - group: nas-emulation-readonly
  - group: nas-games
  - group: nas-games-readonly
  - group: nas-backups
  - group: nas-fullaccess
  - group: nas-shared-space
  - group: nas-shared-space-readonly
  - group: nas-internal
  - group: nas-internal-readonly
  - group: nas-temp-shares


#Even with these users, still have to set the samba passwords
cockpit_users:
  - user: qbit
    password: 'k8s.pass'
    groups: ['qbit', 'nas-plex-media', 'nas-emulation','nas-emulation-roms']
  - user: plex
    password: "k8s.pass"
    groups: ['plex','nas-plex-media']
  - user: k8s
    password: "k8s.pass"
    groups: ['k8s']
  - user: unrarer
    password: "k8s.pass"
    groups: ['7zip']
  - user: torque
    password: torque.pass
    groups: ['sudo', 'nas-fullaccess']
  - user: fileshare-test
    password: default.pass
    groups: ['nas-emulation-roms-readonly','nas-emulation-readonly','nas-shared-space','nas-games-readonly','nas-temp-shares']
  - user: asseenontv
    password: default.pass
    groups: ['nas-emulation-roms-readonly','nas-emulation-readonly','nas-shared-space','nas-games-readonly','nas-temp-shares', 'nas-download-requests']
  - user: eagle07
    password: default.pass
    groups: ['nas-emulation-roms','nas-emulation','nas-shared-space','nas-games','nas-temp-shares', 'nas-download-requests']
