apiVersion: v1
kind: Config
clusters:
- name: "local"
  cluster:
    server: "https://10.1.1.10/k8s/clusters/local"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GN4TWpFdwpNREV4TWpBZUZ3MHlOREEwTURJeU16SXhOVEphRncwek5EQXpNekV5TXpJeE5USmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56RXlNVEF3TVRFeU1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRXNWK1B5VXNDOG4xRwp6OFRaamhIVHlpSi9KMlZMMkNqcENXVCtGd\
      VRBeXZFaHQ3a0R5Y2lsS2pGM1Q1bGJKdVl6ZnNJN2JyVVNLNHRvClVpVmZUSUlaSUtOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGT\
      kM2cy9aUzFFdmoydGtCcWFRNDVCYWxBOGtvTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUErVgptb\
      TFpc0d2YzhXQWRUZWtQelUzNHVYaTV3K2MzWEJtUjFLL200RGdDQWlFQW56VDFWUERIOFl5VEpTe\
      kloekpKCmp0dnBJOVdud1ZKN0VpZEVleGJxRE9RPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "local"
  user:
    token: "kubeconfig-user-s5zg6p65jw:5r7bdwf4dbgjnl9nqwbbd2x2jcqwxl7wdsmmt6gqw97qmqwh2djdf7"


contexts:
- name: "local"
  context:
    user: "local"
    cluster: "local"

current-context: "local"
