apiVersion: v1
kind: Config
clusters:
- name: "local"
  cluster:
    server: "https://10.1.5.10/k8s/clusters/local"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GN4TWpJNApPRGt6TkRBZUZ3MHlOREEwTURVd016UTROVFJhRncwek5EQTBNRE13TXpRNE5UUmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56RXlNamc0T1RNME1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRXJWdi9RODg3MzJlKworZFN6RWFkWHh0em80Wnkya3JoUmo0YkFHM\
      TZPU01DTFU1M3BzdDNYTDdUZm1PL3ZjQjN0K3h2ODVpeVcvYWpSCmd1V0FYaWdFZDZOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGQ\
      WZ4NWtPdGN3WGN1cEEra28yc3VVbkJacUk3TUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUZoQQorV\
      zJWWmRvSWdKSitpa3c4bXZ3amg4b29Leml5Rm9iVVZtNjg3Z2JXQWlFQWpYWEZsbmNaU3JjdGd6W\
      HlndnllCmpjZTh6cUlxb2RNcVZBRzNkblViYUNnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "local"
  user:
    token: "kubeconfig-user-w2xw5rfcg6:lk2lm22w2nrnknr26f5zzg5tkc7c9kgggzlm7kggc6hxzdtpjgfxh5"


contexts:
- name: "local"
  context:
    user: "local"
    cluster: "local"

current-context: "local"
