terraform_role: TerraformProv
terraform_user: terraform-prov@pve
terraform_privs: "VM.Allocate VM.Clone VM.Config.CDROM VM.Config.CPU VM.Config.Cloudinit VM.Config.Disk VM.Config.HWType VM.Config.Memory VM.Config.Network VM.Config.Options VM.Monitor VM.Audit VM.PowerMgmt Datastore.AllocateSpace Datastore.Audit"
ciuser: techdufus

## Ubuntu Server 22.04: Jammy ##
template_vm_id_2204: 9000
template_vm_name_2204: "ubuntu-server-22.04-template"
template_url_2204: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
template_file_2204: jammy-server-cloudimg-amd64.img

## Ubuntu Server 20.04: Focal ##
template_vm_id_2004: 9001
template_vm_name_2004: "ubuntu-server-20.04-template"
template_url_2004: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
template_file_2004: focal-server-cloudimg-amd64.img

## Zabbix Appliance 6.0.4 ##
template_vm_id_zabbix: 9003
template_vm_name_zabbix: "zabbix-appliance"
template_url_zabbix: https://cdn.zabbix.com/zabbix/appliances/stable/6.0/6.0.4/zabbix-appliance-6.0.4-qcow2.tar.gz


firewall_config_files:
  - /etc/pve/nodes/proxmox/host.fw


template_storage: local-lvm
ip_config: ip=dhcp
github_keys: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDYjmlSd0iE+QyWQReb0kZk2C4s/682CpuT1PNDBP9+YQ8nmTSXrPvse4uptpORNXRdQZC4JK7Xi2WQVzur5dVMxRDgr0RoBv6CuskhIIfe0iKnNk7coldcVPGY+Ff7vJX86c2rzzaq7+C3uRO+TDiWSJ/7DtdTeyV7pHOcoYs49aa/d6vS6uN6i5RW+3X+CmE4t5Mnm4ZCFv1KwsMC0PVjH4FIVmynU7qZ7a2LaTEgiNFgtOlLk2Ccnbu+n2OOHkUysvZR4SejzOAsuckFFMH06c6OIqEa5YKlTQlqqGIJGndeh4+jiS2N1TEWa3ZylJk2kbKCriSgiwOzfeC5or9AlS19w1hmX8a3RG2twdJfovfQUcnxcQ+E3kM2hbGAC2QvqONnI/6mrjT6UK7FM2afFY7wQKQmE6Wi0J6Yb71ue0hzz6ggVHtANFMkXH15bTboScjSQgrTvqRwhSKajV1/Gla51+le8KsjBmq05lG6L0cHtt9acm9qCkyIWpRBhuX1kWlf0V9vEsHcDBZ5sVlWvXMyTTWm2GHJAV5SpRJdRNwRi3ScffMUDLrx8HSAMKnaCp+ejcEsUbIWIQaOQLduGiaVQ+Npt4NkO0l1uvwjPPGKlCEcQOygjhOMVxlKECdU+MsApi/by5p8f0K+6PFkTFGNqKidDK6fmhI97FYVwQ=="
